### ISSUE TITLE
傻逼东西

### ISSUE THREAD

**Issue by NullPointerException-Jy** [chenbimo/yicode-cli#1]
小厂用不着 大厂不会用

**Comment by sjlleo** [comment]
无论如何，你都不应该对一个开源社区的开发者进行人身攻击，发`Issue`要有对人最基本的尊重。

你肯定没有读 [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines)，`Respect each other`难道不懂么。

再说，如果你不喜欢用，不用就行了，也没人逼着你用是吧？

**Comment by chenbimo** [comment]
> 无论如何，你都不应该对一个开源社区的开发者进行人身攻击，发`Issue`要有对人最基本的尊重。
> 
> 你肯定没有读 [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines)，`Respect each other`难道不懂么。
> 
> 再说，如果你不喜欢用，不用就行了，也没人逼着你用是吧？

无妨，不理就行了。
